"""
run_sql.py
----------
Runs every SQL file in /sql (in order) against a local SQLite database and saves
the result of each query to outputs/sql_results/<query_name>.csv. It also writes
outputs/SQL_RESULTS.md so the results can be read directly on GitHub.

Queries are marked in the .sql files with a comment line:
    -- @query: <name> | <description>
Everything before the first marker (CREATE / INSERT statements) is executed as a
script; each marked block is run as a single SELECT query.

Run:  python scripts/run_sql.py
"""

import re
import sqlite3
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SQL_DIR = ROOT / "sql"
DB_PATH = ROOT / "data" / "sales.db"
RESULTS_DIR = ROOT / "outputs" / "sql_results"
REPORT = ROOT / "outputs" / "SQL_RESULTS.md"

# CSV files loaded into the database before the SQL scripts run
STAGING_TABLES = {"sales_raw": ROOT / "data" / "raw" / "sales_raw.csv"}

MARKER = re.compile(r"^--\s*@query:\s*(?P<name>[\w]+)\s*\|\s*(?P<desc>.+)$", re.MULTILINE)


def snake_case(col: str) -> str:
    return re.sub(r"[^0-9a-zA-Z]+", "_", col).strip("_").lower()


def split_sql(text: str):
    """Return (setup_script, [(name, description, query), ...])."""
    matches = list(MARKER.finditer(text))
    setup = text[: matches[0].start()] if matches else text
    queries = []
    for i, m in enumerate(matches):
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        query = text[m.end():end].strip().rstrip(";").strip()
        queries.append((m["name"], m["desc"].strip(), query))
    return setup, queries


def main() -> None:
    DB_PATH.unlink(missing_ok=True)
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)

    for table, csv_path in STAGING_TABLES.items():
        df = pd.read_csv(csv_path)
        df.columns = [snake_case(c) for c in df.columns]
        df.to_sql(table, conn, index=False)
        print(f"Loaded {csv_path.name} -> table `{table}` ({len(df):,} rows)")

    report = ["# SQL Results\n",
              "Auto-generated by `scripts/run_sql.py`. Each section shows the query "
              "name, the question it answers and its output (first 15 rows).\n"]

    n_queries = 0
    for sql_file in sorted(SQL_DIR.glob("*.sql")):
        setup, queries = split_sql(sql_file.read_text(encoding="utf-8"))
        if setup.strip():
            conn.executescript(setup)
            conn.commit()
        report.append(f"\n## `{sql_file.name}`\n")
        print(f"\n== {sql_file.name} ==")
        for name, desc, query in queries:
            result = pd.read_sql_query(query, conn)
            result.to_csv(RESULTS_DIR / f"{name}.csv", index=False)
            n_queries += 1
            print(f"  [ok] {name:<40} {len(result):>4} rows")
            report.append(f"\n### {name}\n**{desc}**\n")
            report.append(result.head(15).to_markdown(index=False))
            report.append("")

    conn.close()
    REPORT.write_text("\n".join(report), encoding="utf-8")
    print(f"\n{n_queries} queries ran successfully.")
    print(f"Results -> {RESULTS_DIR.relative_to(ROOT)}/  |  Report -> {REPORT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
